/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AdminController;
import controller.PenjualanController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.PenjualanModel;

/**
 *
 * @author Abo
 */
public class FrmInputData extends javax.swing.JFrame {

    private PenjualanController control;
    private boolean status;
    private String proses;
    private List<PenjualanModel> listPenjualan;
    private String[] tabelHeader;
    private DefaultTableModel dtm;
    private int row;
    int total = 0;
    int idPeriod = 1;
    int jumlahPenjualan = 0;
    int jumlahPeriode = 0;
    int kuadrat = 0;
    int jumpenju = 0;
    int sementara = 0;
    float b = 0;

    public void TampilData() {

        txtIdPeriode.setText(String.valueOf(idPeriod));

    }

    /**
     * Creates new form FrmInputData
     */
    public FrmInputData() {
        initComponents();
        control = new PenjualanController(this);
        TampilData();

        tabelHeader = new String[]{"Id Periode", "Jumlah Penjualan"};
        dtm = new DefaultTableModel(null, tabelHeader);
        tblData.setModel(dtm);
    }

    public void refresh() {
        dtm = (DefaultTableModel) tblData.getModel();
        dtm.setRowCount(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_input = new javax.swing.JPanel();
        lbl_logo = new javax.swing.JLabel();
        lbl_input_data = new javax.swing.JLabel();
        lbl_catatan = new javax.swing.JLabel();
        btn_cari = new javax.swing.JButton();
        btn_proses = new javax.swing.JButton();
        btn_cleartbl = new javax.swing.JButton();
        lbl_idPeriode = new javax.swing.JLabel();
        lbl_jml = new javax.swing.JLabel();
        txtIdPeriode = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        btn_input = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_periode = new javax.swing.JLabel();
        txtHasil = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtKuadrat = new javax.swing.JTextField();
        txtKuadratkaliJumlah = new javax.swing.JTextField();
        txtJumlahPenjualan = new javax.swing.JTextField();
        txtJumlahPeriode = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSemKuadrat = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSemPed = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtKuadratPeriode = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtB = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_logo.setText("Logo Toko");

        lbl_input_data.setFont(new java.awt.Font("Stencil Std", 1, 18)); // NOI18N
        lbl_input_data.setText("INPUT DATA");

        lbl_catatan.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lbl_catatan.setText("*Catatan : 1. Isikan kolom \"Jumlah Penjualan\" lalu ");

        btn_cari.setText("PENCARIAN HASIL");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        btn_proses.setText("PROSES");
        btn_proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prosesActionPerformed(evt);
            }
        });

        btn_cleartbl.setText("KOSONGKAN TABEL");
        btn_cleartbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cleartblActionPerformed(evt);
            }
        });

        lbl_idPeriode.setText("Id Periode :");

        lbl_jml.setText("Jumlah Penjualan  :");

        txtIdPeriode.setEditable(false);

        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Periode", "Periode Penjualan", "Jumlah Penjualan"
            }
        ));
        jScrollPane1.setViewportView(tblData);

        btn_input.setText("INPUT");
        btn_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inputActionPerformed(evt);
            }
        });

        jLabel1.setText("klik tombol \"INPUT\"");

        jLabel2.setText("2. Setelah selesai input data, selanjutnya");

        jLabel3.setText("klik tombol \"PROSES\"");

        lbl_periode.setText("hasil sem");

        jLabel4.setText("P");

        jLabel5.setText("J");

        jLabel6.setText("K");

        jLabel7.setText("K*J");

        txtKuadrat.setEditable(false);

        txtKuadratkaliJumlah.setEditable(false);

        txtJumlahPenjualan.setEditable(false);

        txtJumlahPeriode.setEditable(false);

        jLabel8.setText("Kuadrat");

        txtSemKuadrat.setText("jLabel9");

        jLabel10.setText("X*Y");

        txtSemPed.setText("jLabel9");

        jLabel9.setText("KP");

        txtKuadratPeriode.setText("jLabel11");

        jLabel11.setText("b");

        txtB.setText("jLabel12");

        jLabel12.setText("a");

        txtA.setText("jLabel13");

        javax.swing.GroupLayout panel_inputLayout = new javax.swing.GroupLayout(panel_input);
        panel_input.setLayout(panel_inputLayout);
        panel_inputLayout.setHorizontalGroup(
            panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_inputLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbl_logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_input_data)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSemKuadrat)
                .addContainerGap())
            .addGroup(panel_inputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
            .addGroup(panel_inputLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btn_proses, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cleartbl)
                .addGap(76, 76, 76))
            .addGroup(panel_inputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cari)
                    .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_inputLayout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtA))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_inputLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(30, 30, 30)
                            .addComponent(txtB))))
                .addGap(18, 18, 18)
                .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_inputLayout.createSequentialGroup()
                        .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_inputLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel1))
                            .addGroup(panel_inputLayout.createSequentialGroup()
                                .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtIdPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panel_inputLayout.createSequentialGroup()
                                            .addComponent(lbl_jml)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lbl_idPeriode))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_inputLayout.createSequentialGroup()
                                        .addComponent(lbl_periode)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btn_input, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(63, 63, 63))
                    .addGroup(panel_inputLayout.createSequentialGroup()
                        .addComponent(lbl_catatan)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtKuadratPeriode)
                        .addContainerGap())
                    .addGroup(panel_inputLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panel_inputLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(140, 140, 140))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_inputLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(panel_inputLayout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(37, 37, 37)
                                            .addComponent(jLabel6))
                                        .addComponent(jLabel7))
                                    .addGap(18, 18, 18)
                                    .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panel_inputLayout.createSequentialGroup()
                                            .addComponent(txtKuadrat, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4))
                                        .addGroup(panel_inputLayout.createSequentialGroup()
                                            .addComponent(txtKuadratkaliJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5)))
                                    .addGap(18, 18, 18)
                                    .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtJumlahPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtJumlahPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(40, 40, 40)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_inputLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSemPed)
                                .addContainerGap())))))
        );
        panel_inputLayout.setVerticalGroup(
            panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_inputLayout.createSequentialGroup()
                .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_inputLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_logo)
                            .addComponent(lbl_input_data)))
                    .addGroup(panel_inputLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtSemKuadrat))))
                .addGap(4, 4, 4)
                .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtSemPed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_catatan)
                    .addComponent(jLabel9)
                    .addComponent(txtKuadratPeriode)
                    .addComponent(jLabel11)
                    .addComponent(txtB))
                .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_inputLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(panel_inputLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtA))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_inputLayout.createSequentialGroup()
                        .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(txtKuadrat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(txtKuadratkaliJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_cari)
                            .addComponent(lbl_idPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_periode))
                        .addGap(12, 12, 12)
                        .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_jml)
                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_input, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_proses)
                            .addComponent(btn_cleartbl)))
                    .addGroup(panel_inputLayout.createSequentialGroup()
                        .addComponent(txtJumlahPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(txtJumlahPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cleartblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cleartblActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_cleartblActionPerformed

    private void btn_prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prosesActionPerformed
        // TODO add your handling code here:
        
        b = (((idPeriod-1)*jumpenju) - (jumlahPeriode*jumlahPenjualan));
        float b2= (((idPeriod-1)*kuadrat)-sementara);
        float hasilb = b/b2;
        txtB.setText(String.valueOf(hasilb));
        
        float a = jumlahPenjualan - ((hasilb*jumlahPeriode));
        float a1 = a/(idPeriod-1);
        txtA.setText(String.valueOf(a1));
        
        float fix = a1+(hasilb*idPeriod);
        txtHasil.setText(String.valueOf(fix));
    }//GEN-LAST:event_btn_prosesActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        FrmPencarianHasil form = new FrmPencarianHasil();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inputActionPerformed
        // TODO add your handling code here:
        txtIdPeriode.setText(String.valueOf(idPeriod));
        jumlahPenjualan = jumlahPenjualan + Integer.parseInt(txtJumlah.getText());
        jumlahPeriode = jumlahPeriode + idPeriod;
        
        int Semkuadrat =idPeriod*idPeriod;
        int SemPenPed = idPeriod*Integer.parseInt(txtJumlah.getText());
        kuadrat = kuadrat+Semkuadrat;
        jumpenju = jumpenju+SemPenPed;
        
        
        txtJumlahPeriode.setText(String.valueOf(jumlahPeriode));
        txtJumlahPenjualan.setText(String.valueOf(jumlahPenjualan));
        txtKuadrat.setText(String.valueOf(kuadrat));
        txtKuadratkaliJumlah.setText(String.valueOf(jumpenju));
        txtSemKuadrat.setText(String.valueOf(Semkuadrat));
        txtSemPed.setText(String.valueOf(SemPenPed));
        sementara = Integer.parseInt(txtJumlahPeriode.getText())*Integer.parseInt(txtJumlahPeriode.getText());
        txtKuadratPeriode.setText(String.valueOf(sementara));
        dtm.addRow(new Object[]{
            txtIdPeriode.getText(), txtJumlah.getText()});

//        control.inputPenjualan(txtIdPeriode.getText(), txtJumlah.getText(), txtPeriode.getText());
//        boolean hasil = control.insertPenjualan();
//        if(hasil == false){
//            
//        }
//            String o = (String)dtm.getValueAt(1,1);
//            int x = Integer.parseInt(o);
//            txtHasil.setText(String.valueOf(x));
        idPeriod = idPeriod + 1;
        txtJumlah.setText("");
    }//GEN-LAST:event_btn_inputActionPerformed

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInputData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInputData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInputData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInputData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInputData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_cleartbl;
    private javax.swing.JButton btn_input;
    private javax.swing.JButton btn_proses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_catatan;
    private javax.swing.JLabel lbl_idPeriode;
    private javax.swing.JLabel lbl_input_data;
    private javax.swing.JLabel lbl_jml;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_periode;
    private javax.swing.JPanel panel_input;
    private javax.swing.JTable tblData;
    private javax.swing.JLabel txtA;
    private javax.swing.JLabel txtB;
    private javax.swing.JTextField txtHasil;
    private javax.swing.JTextField txtIdPeriode;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtJumlahPenjualan;
    private javax.swing.JTextField txtJumlahPeriode;
    private javax.swing.JTextField txtKuadrat;
    private javax.swing.JLabel txtKuadratPeriode;
    private javax.swing.JTextField txtKuadratkaliJumlah;
    private javax.swing.JLabel txtSemKuadrat;
    private javax.swing.JLabel txtSemPed;
    // End of variables declaration//GEN-END:variables

    private void insertPenjualan() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
