/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 *
 * @author Abo
 */
public class FrmPencarianHasil extends javax.swing.JFrame {

    /** Creates new form FrmPencarianHasil */
    public FrmPencarianHasil() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_pencarian = new javax.swing.JPanel();
        lbl_logo = new javax.swing.JLabel();
        lbl_laporan_hasil = new javax.swing.JLabel();
        lbl_forecasting = new javax.swing.JLabel();
        panel_laporan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea_hasil_bulan_x = new javax.swing.JTextArea();
        btn_kembali = new javax.swing.JButton();
        btn_cetak = new javax.swing.JButton();
        cmb_bulan = new javax.swing.JComboBox<>();
        lbl_bulan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_logo.setText("Logo Toko");

        lbl_laporan_hasil.setFont(new java.awt.Font("Stencil Std", 1, 18)); // NOI18N
        lbl_laporan_hasil.setText("LAPORAN HASIL");

        lbl_forecasting.setFont(new java.awt.Font("Stencil Std", 1, 18)); // NOI18N
        lbl_forecasting.setText("FORECASTING");

        panel_laporan.setBackground(new java.awt.Color(204, 204, 255));

        txtArea_hasil_bulan_x.setColumns(20);
        txtArea_hasil_bulan_x.setRows(5);
        jScrollPane1.setViewportView(txtArea_hasil_bulan_x);

        javax.swing.GroupLayout panel_laporanLayout = new javax.swing.GroupLayout(panel_laporan);
        panel_laporan.setLayout(panel_laporanLayout);
        panel_laporanLayout.setHorizontalGroup(
            panel_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_laporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_laporanLayout.setVerticalGroup(
            panel_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_laporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_kembali.setText("KEMBALI");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });

        btn_cetak.setText("CETAK");

        cmb_bulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_bulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_bulanActionPerformed(evt);
            }
        });

        lbl_bulan.setText("Pilih periode penjualan :");

        javax.swing.GroupLayout panel_pencarianLayout = new javax.swing.GroupLayout(panel_pencarian);
        panel_pencarian.setLayout(panel_pencarianLayout);
        panel_pencarianLayout.setHorizontalGroup(
            panel_pencarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pencarianLayout.createSequentialGroup()
                .addGroup(panel_pencarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_pencarianLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lbl_bulan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_bulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_pencarianLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panel_pencarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_pencarianLayout.createSequentialGroup()
                                .addComponent(lbl_logo)
                                .addGap(77, 77, 77)
                                .addGroup(panel_pencarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_laporan_hasil)
                                    .addGroup(panel_pencarianLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lbl_forecasting))))))
                    .addGroup(panel_pencarianLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btn_kembali)
                        .addGap(84, 84, 84)
                        .addComponent(btn_cetak)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panel_pencarianLayout.setVerticalGroup(
            panel_pencarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pencarianLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel_pencarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_logo)
                    .addComponent(lbl_laporan_hasil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_forecasting)
                .addGap(30, 30, 30)
                .addGroup(panel_pencarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_bulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_bulan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_pencarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_kembali)
                    .addComponent(btn_cetak))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_bulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_bulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_bulanActionPerformed

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
        FrmInputData form = new FrmInputData();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPencarianHasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPencarianHasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPencarianHasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPencarianHasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPencarianHasil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JComboBox<String> cmb_bulan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_bulan;
    private javax.swing.JLabel lbl_forecasting;
    private javax.swing.JLabel lbl_laporan_hasil;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JPanel panel_laporan;
    private javax.swing.JPanel panel_pencarian;
    private javax.swing.JTextArea txtArea_hasil_bulan_x;
    // End of variables declaration//GEN-END:variables

}
